---
name: DuoMus
version: v0.1.0
slug: duomus
description: DuoMus support tools and web interface forwarder.
url: https://github.com/focusware-develop/addon-duomus
startup: services
panel_icon: mdi:temperature-celsius
panel_title: Duo Mus
ingress: true
init: false
arch:
  - aarch64
  - amd64
host_network: true
host_dbus: true
devices:
  - /dev/ttyAMA0
  - /dev/ttyACM0
  - /dev/ttyAMA10
privileged:
  - SYS_ADMIN
  - SYS_RESOURCE
map:
  - addon_config:rw
options:
  ipaddress: ""
schema:
  ipaddress: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
