---
name: DuoMus
version: v0.0.3
slug: duomus
description: DuoMus support tools
url: https://github.com/focusware-develop/addon-duomus
startup: services
panel_icon: mdi:temperature-celsius
init: false
arch:
  - aarch64
  - amd64
host_network: true
host_dbus: true
devices:
  - /dev/ttyAMA0
  - /dev/ttyACM0
  - /dev/ttyAMA10
privileged:
  - SYS_ADMIN
  - SYS_RESOURCE
map:
  - addon_config:rw
options:
  ipaddress: ""
schema:
  ipaddress: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
